# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Game
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
yarn_mappings_patch_neoforge_version = 1.21+build.6
minecraft_compat_version=1.21.11

# Loader
enabled_platforms = fabric,neoforge
fabric_loader_version=0.19.3
neoforge_version = 21.11.45

# Mod
maven_group=net.rpg_series
archives_name=wizards
mod_version=3.2.0.001

# Dependencies
fabric_api_version=0.141.6+1.21.11
tiny_config_version=3.1.1
cloth_config_version=21.11.153
player_anim_version=1.1.10+mc.1.21.11

armor_model_api_version=1.1.0.003+1.21.11
runes_version=1.4.0.006+1.21.11
structure_pool_api_version=1.3.0.001+1.21.11
spell_power_version=1.7.0.001+1.21.11
spell_engine_version=1.11.0.003+1.21.11
ranged_weapon_api_version=3.1.0.002+1.21.11

# Fabric only
cardinal_components_version=7.3.0
trinkets_version=3.11.0-beta.2+1.21.11
mod_menu_version=17.0.0

# NeoForge only
curios_version=14.0.0+1.21.11
