modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ZsoltMolnarrr/Wizards/issues"
license = "All Rights Reserved"

[[mods]]
modId = "wizards"
version = "${version}"
displayName = "Wizards (RPG Series)"
authors = "Daedelus"
description = '''
Destroy your enemies with Arcane, Fire and Frost magic.
'''
logoFile = "icon.png"

[[dependencies.wizards]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wizards]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wizards]]
modId = "azurelibarmor"
type = "required"
versionRange = "[${azure_lib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wizards]]
modId = "spell_engine"
type = "required"
versionRange = "[${spell_engine_version},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.wizards]]
modId = "runes"
type = "required"
versionRange = "[${runes_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wizards]]
modId = "structure_pool_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "wizards.mixins.json"
